name: toastify_flutter
description: "A simple plugin to show custom toasts in Flutter apps"
version: 1.0.0
homepage: https://github.com/cristianlag97/toastify_flutter

environment:
  sdk: '>=3.3.3 <4.0.0'
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0


flutter:
  plugin:
    platforms:
      android:
        package: https://pub.dev/packages/toastify_flutter/score
        pluginClass: ToastifyFlutter
      ios:
        package: https://pub.dev/packages/toastify_flutter/score
        pluginClass: ToastifyFlutter